artifact_uri: file:///F:/Data Science/ML Projects 22-09-2023/Real estate project/your_mlflow_tracking_uri/0/d58d0af85f73432ba115c6065115ccbb/artifacts
end_time: 1709102739942
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: d58d0af85f73432ba115c6065115ccbb
run_name: mysterious-stork-161
run_uuid: d58d0af85f73432ba115c6065115ccbb
source_name: ''
source_type: 4
source_version: ''
start_time: 1709102406282
status: 3
tags: []
user_id: jnoot
