artifact_uri: file:///F:/Data Science/ML Projects 22-09-2023/Real estate project/your_mlflow_tracking_uri/0/3af09c4caf8e4381920d7896f116eb8f/artifacts
end_time: 1709102213531
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 3af09c4caf8e4381920d7896f116eb8f
run_name: beautiful-gnu-632
run_uuid: 3af09c4caf8e4381920d7896f116eb8f
source_name: ''
source_type: 4
source_version: ''
start_time: 1709101840049
status: 4
tags: []
user_id: jnoot
