artifact_uri: file:///F:/Data Science/ML Projects 22-09-2023/Real estate project/your_mlflow_tracking_uri/0/58a54efb42d14532af942980ce5fe2a2/artifacts
end_time: 1709102529632
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 58a54efb42d14532af942980ce5fe2a2
run_name: abundant-koi-961
run_uuid: 58a54efb42d14532af942980ce5fe2a2
source_name: ''
source_type: 4
source_version: ''
start_time: 1709102406282
status: 3
tags: []
user_id: jnoot
