artifact_uri: file:///F:/Data Science/ML Projects 22-09-2023/Real estate project/your_mlflow_tracking_uri/0/cf99c02847e844969e2a8a768ce10df8/artifacts
end_time: 1709101352344
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: cf99c02847e844969e2a8a768ce10df8
run_name: zealous-shark-484
run_uuid: cf99c02847e844969e2a8a768ce10df8
source_name: ''
source_type: 4
source_version: ''
start_time: 1709101214513
status: 4
tags: []
user_id: jnoot
