artifact_uri: file:///F:/Data Science/ML Projects 22-09-2023/Real estate project/your_mlflow_tracking_uri/0/f5c5b1ff69184f5181b9d3da62cd8516/artifacts
end_time: 1709101963701
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f5c5b1ff69184f5181b9d3da62cd8516
run_name: amusing-shoat-851
run_uuid: f5c5b1ff69184f5181b9d3da62cd8516
source_name: ''
source_type: 4
source_version: ''
start_time: 1709101840049
status: 3
tags: []
user_id: jnoot
