artifact_location: file:///F:/Data Science/ML Projects 22-09-2023/Real estate project/your_mlflow_tracking_uri/0
creation_time: 1709101214278
experiment_id: '0'
last_update_time: 1709101214278
lifecycle_stage: active
name: Default
