artifact_uri: file:///F:/Data Science/ML Projects 22-09-2023/Real estate project/your_mlflow_tracking_uri/0/71c36cb91fcd4a11aa1a5d9464e358ce/artifacts
end_time: 1709102529632
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 71c36cb91fcd4a11aa1a5d9464e358ce
run_name: useful-stork-126
run_uuid: 71c36cb91fcd4a11aa1a5d9464e358ce
source_name: ''
source_type: 4
source_version: ''
start_time: 1709102406282
status: 3
tags: []
user_id: jnoot
