artifact_uri: file:///F:/Data Science/ML Projects 22-09-2023/Real estate project/your_mlflow_tracking_uri/0/f050c8e68bd04c0eb49dc9cc85bb6492/artifacts
end_time: 1709103004662
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f050c8e68bd04c0eb49dc9cc85bb6492
run_name: nimble-stork-31
run_uuid: f050c8e68bd04c0eb49dc9cc85bb6492
source_name: ''
source_type: 4
source_version: ''
start_time: 1709102860999
status: 3
tags: []
user_id: jnoot
