artifact_uri: file:///F:/Data Science/ML Projects 22-09-2023/Real estate project/your_mlflow_tracking_uri/0/4f057acc94be419185a1fae3b01e9ec9/artifacts
end_time: 1709102179358
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 4f057acc94be419185a1fae3b01e9ec9
run_name: casual-mouse-244
run_uuid: 4f057acc94be419185a1fae3b01e9ec9
source_name: ''
source_type: 4
source_version: ''
start_time: 1709101840049
status: 3
tags: []
user_id: jnoot
