artifact_uri: file:///F:/Data Science/ML Projects 22-09-2023/Real estate project/your_mlflow_tracking_uri/0/58bcfdaa8afe42bfaa5181906a4e0739/artifacts
end_time: 1709102529632
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 58bcfdaa8afe42bfaa5181906a4e0739
run_name: delicate-cub-540
run_uuid: 58bcfdaa8afe42bfaa5181906a4e0739
source_name: ''
source_type: 4
source_version: ''
start_time: 1709102406282
status: 3
tags: []
user_id: jnoot
