artifact_uri: file:///F:/Data Science/ML Projects 22-09-2023/Real estate project/your_mlflow_tracking_uri/0/2febd9a8b1174beb82d68aa011ec95b0/artifacts
end_time: 1709102529632
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 2febd9a8b1174beb82d68aa011ec95b0
run_name: delicate-dog-285
run_uuid: 2febd9a8b1174beb82d68aa011ec95b0
source_name: ''
source_type: 4
source_version: ''
start_time: 1709102406282
status: 3
tags: []
user_id: jnoot
