artifact_uri: file:///F:/Data Science/ML Projects 22-09-2023/Real estate project/your_mlflow_tracking_uri/0/6f351e8b65ab41f2876c58dd9900706d/artifacts
end_time: 1709101963701
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 6f351e8b65ab41f2876c58dd9900706d
run_name: delicate-mole-835
run_uuid: 6f351e8b65ab41f2876c58dd9900706d
source_name: ''
source_type: 4
source_version: ''
start_time: 1709101840049
status: 3
tags: []
user_id: jnoot
