artifact_uri: file:///F:/Data Science/ML Projects 22-09-2023/Real estate project/your_mlflow_tracking_uri/0/f6719b19e361427fbbcea3afbb3ef6be/artifacts
end_time: 1709102529632
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f6719b19e361427fbbcea3afbb3ef6be
run_name: thundering-moth-182
run_uuid: f6719b19e361427fbbcea3afbb3ef6be
source_name: ''
source_type: 4
source_version: ''
start_time: 1709102406282
status: 3
tags: []
user_id: jnoot
