channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=22.3.1
- pip:
  - mlflow==2.10.2
  - catboost==1.2.3
  - cloudpickle==2.2.1
  - ipywidgets==8.1.2
  - numpy==1.26.4
  - packaging==23.2
  - pandas==2.2.1
  - psutil==5.9.8
  - pyyaml==6.0.1
  - scikit-learn==1.4.1.post1
  - scipy==1.12.0
  - xgboost==2.0.3
name: mlflow-env
