artifact_uri: file:///F:/Data Science/ML Projects 22-09-2023/Real estate project/your_mlflow_tracking_uri/0/98ad1087ca3b4f05b8d64befb751f02e/artifacts
end_time: 1709102179358
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 98ad1087ca3b4f05b8d64befb751f02e
run_name: placid-squirrel-688
run_uuid: 98ad1087ca3b4f05b8d64befb751f02e
source_name: ''
source_type: 4
source_version: ''
start_time: 1709101840049
status: 3
tags: []
user_id: jnoot
