artifact_uri: file:///F:/Data Science/ML Projects 22-09-2023/Real estate project/your_mlflow_tracking_uri/0/7232d50a76d4487ab5e00dca1c973558/artifacts
end_time: 1709101963701
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 7232d50a76d4487ab5e00dca1c973558
run_name: serious-midge-234
run_uuid: 7232d50a76d4487ab5e00dca1c973558
source_name: ''
source_type: 4
source_version: ''
start_time: 1709101840049
status: 3
tags: []
user_id: jnoot
