artifact_uri: file:///F:/Data Science/ML Projects 22-09-2023/Real estate project/your_mlflow_tracking_uri/0/9ecec56eecf34919a277a0373b313b3a/artifacts
end_time: 1709102739942
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 9ecec56eecf34919a277a0373b313b3a
run_name: bold-skunk-199
run_uuid: 9ecec56eecf34919a277a0373b313b3a
source_name: ''
source_type: 4
source_version: ''
start_time: 1709102406282
status: 3
tags: []
user_id: jnoot
