artifact_uri: file:///F:/Data Science/ML Projects 22-09-2023/Real estate project/your_mlflow_tracking_uri/0/c636e234177d446eb1bdf19bed2813ff/artifacts
end_time: 1709102739942
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: c636e234177d446eb1bdf19bed2813ff
run_name: worried-wasp-178
run_uuid: c636e234177d446eb1bdf19bed2813ff
source_name: ''
source_type: 4
source_version: ''
start_time: 1709102406282
status: 3
tags: []
user_id: jnoot
