artifact_uri: file:///F:/Data Science/ML Projects 22-09-2023/Real estate project/your_mlflow_tracking_uri/0/73f915cee7554b1dbd3732b169b47898/artifacts
end_time: 1709101341022
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 73f915cee7554b1dbd3732b169b47898
run_name: powerful-crow-564
run_uuid: 73f915cee7554b1dbd3732b169b47898
source_name: ''
source_type: 4
source_version: ''
start_time: 1709101214513
status: 3
tags: []
user_id: jnoot
