artifact_uri: file:///F:/Data Science/ML Projects 22-09-2023/Real estate project/your_mlflow_tracking_uri/0/29f8e964bbb944ff94d41e4be915085d/artifacts
end_time: 1709101341022
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 29f8e964bbb944ff94d41e4be915085d
run_name: righteous-squid-964
run_uuid: 29f8e964bbb944ff94d41e4be915085d
source_name: ''
source_type: 4
source_version: ''
start_time: 1709101214513
status: 3
tags: []
user_id: jnoot
