artifact_uri: file:///F:/Data Science/ML Projects 22-09-2023/Real estate project/your_mlflow_tracking_uri/0/15b1fc81b4254a5f86794f907618ca13/artifacts
end_time: 1709101963701
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 15b1fc81b4254a5f86794f907618ca13
run_name: colorful-wolf-595
run_uuid: 15b1fc81b4254a5f86794f907618ca13
source_name: ''
source_type: 4
source_version: ''
start_time: 1709101840049
status: 3
tags: []
user_id: jnoot
