artifact_uri: file:///F:/Data Science/ML Projects 22-09-2023/Real estate project/your_mlflow_tracking_uri/0/1ae50aab220a4d11925de9ebe8d16074/artifacts
end_time: 1709101341022
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 1ae50aab220a4d11925de9ebe8d16074
run_name: spiffy-slug-950
run_uuid: 1ae50aab220a4d11925de9ebe8d16074
source_name: ''
source_type: 4
source_version: ''
start_time: 1709101214513
status: 3
tags: []
user_id: jnoot
