artifact_uri: file:///F:/Data Science/ML Projects 22-09-2023/Real estate project/your_mlflow_tracking_uri/0/b577c2addd134d4e8f0d0bb5f2e9f3e4/artifacts
end_time: 1709101341022
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: b577c2addd134d4e8f0d0bb5f2e9f3e4
run_name: clumsy-fox-208
run_uuid: b577c2addd134d4e8f0d0bb5f2e9f3e4
source_name: ''
source_type: 4
source_version: ''
start_time: 1709101214513
status: 3
tags: []
user_id: jnoot
